# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20170720_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='state',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dojo',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
