# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0003_auto_20170721_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojos_id',
            new_name='dojo',
        ),
    ]
